name: variables
on: 
    push: 
        branches: 
            main
jobs:
    var1:
        runs-on: ubuntu-latest
        steps:
            - name: step1
              run: echo 'env = ${{ vars.user }}'
            - name: stepfor secrets
              run: echo 'env = ${{ secrets.token }}'